### ISSUE TITLE
Question about the calculating dynamic_percentage_threshold method 

### ISSUE THREAD

**Issue by b1ackwater3** [shiliu-egg/ICML2024_COFT#2]
In the paper, the dynamic_percentage_threshold is calculated by :

![image](https://github.com/user-attachments/assets/edde9598-adae-451b-854b-266af9854523)

But in the Code Repo, the `threshold.py 36`  is : 
```python
dynamic_percentage_threshold = 0.5 * min(base_threshold + normalized_token_count, 1)
```
My understanding is that `normalized_token_count` is the `informativeness for each reference context` mentioned in the paper. But the `length of each context` is missed.

If you could answer my ques, I would be extremely grateful.

**Comment by shiliu-egg** [comment]
Thank you for your interest in our paper. In subsequent experiments, we observed that self-information metrics and text length metrics are highly correlated in many cases. To reduce preparation time during the inference phase, we omitted this component when releasing the code. The resulting differences in performance after testing were minimal. You may also incorporate this portion of the code for your own evaluations.

**Comment by b1ackwater3** [comment]
Thanks for answering, so the `self-information metrics` and the `text length metric` are presented in the form of  `normalized_token_count`. I don't know if my understanding is correct. I would be extremely grateful if you could answer me.

**Comment by shiliu-egg** [comment]
Sorry for the delayed response. Yes, the self-information metrics and the text length metric are presented as normalized token counts.
